from flask import jsonify, abort
from api.v1.views import app_views

# Existing routes...
# ...

# New endpoint to raise 401 error
@app_views.route('/unauthorized', methods=['GET'], strict_slashes=False)
def unauthorized_endpoint():
    abort(401)

# Existing routes...
# ...
